## The Basics
site_name: SpamBlockers Documentation
site_url: https://andreijiroheugeniohalili24680.github.io/SpamBlockersBot-Docs

## Repo Info and Links
# Will moved to gitlab:SpamBlockers/docs soon
repo_name: AndreiJirohHaliliDev2006/SpamBlockersBot-Docs
repo_url: https://gitlab.com/AndreiJirohHaliliDev2006/SpamBlockersBot-Docs
edit_uri: edit/master/src/

## Navigation
nav:
  - 'Home': index.md
  - 'Telegram Bot':
    - 'Setting up bot': tg/setup.md
    - 'Commands Reference': tg/commands-reference.md
    - 'Customization': 'tg/customization.md'
  - 'API Documentation':
    - "API Endpoints": 'api-docs/available-endpoints.md'
    - "API Wrappers and CLIs":
      - "Official Wrappers": 'api-docs/packages.md/#official-wrappers'
      - "Official CLI": 'api-docs/packages.md/#official-cli'
      - "Node.js Wrapper": 'https://npmjs.com/package/@SpamBlockers/API'
      - "Node.js CLI": 'https://npmjs.com/package/@SpamBlockers/CLI'
    - "API Permissions": 'api-docs/permissions.md'
    - "Querying the Banlist":: 'api-docs/banlist.md'
    - "FAQs": 'api-docs/faq.md'
  - "Support Chat": 'https://t.me/SpamBlockers'


## Themeing and builds
docs_dir: src
theme:
  language: en
  name: material
  font:
    text: Roboto
    code: Roboto Mono

## Markdown Extensions
## More soon!
markdown_extensions:
  - pyembed.markdown
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      toc_depth: "2"
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys

## Mkdocs Plugins
plugins:
  - search:
      seperator: '[\s\-\.]'
      lang: [ 'en' ]
  - minify:
      minify_html: true
  - git-revision-date-localized

## Extra stuff
extra:
  ## Social icons
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/SpamBlockers'
    - icon: fontawesome/brands/gitlab
      link: 'https://gitlab.com/SpamBlockers'
    - icon: fontawesome/brands/telegram
      link: 'https://telegram.dog/SpamBlockers'