## The Basics
site_name: SpamBlockers Documentation
site_url: https://andreijiroheugeniohalili24680.github.io/SpamBlockersBot-Docs

## Repo Info and Links
# Will moved to lungers/SpamBlockersBot-Docs soon
repo_name: AndreiJirohHaliliDev2006/SpamBlockersBot-Docs
repo_url: https://gitlab.com/AndreiJirohHaliliDev2006/SpamBlockersBot-Docs
edit_uri: edit/master/src/

## Navigation
nav:
  - 'Home': index.md
  - 'Telegram Bot':
    - 'Setting up the server': tg/setup.md
    - 'Commands Reference': tg/commands-reference.md
  - 'API Documentation':
    - "API Endpoints": api/available-endpoints.md
    - "API Wrappers Usage": api/wrappers.md

## Themeing and builds
docs_dir: src
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono

## Markdown Extensions
## More soon!
markdown_extensions:
  - pyembed.markdown
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      toc_depth: "2"
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys

## Mkdocs Plugins
plugins:
  - search
  - git-revision-date-localized