name: Build the site and deploy to GitHub Pages

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip to latest version
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get the dependency cache directory
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Generate documentation site
        run: mkdocs build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ## Push to 'gh-pages' branch from the 'site' branch
          publish_dir: ./site
          # defaults to 'gh-pages' if undefined, but we'll do this to make
          # sure we're not messing stuff with it.
          publish_branch: gh-pages
          ## More config blah blah.
          allow_empty_commit: false
          keep_files: true
          ## Committer Info & Commit Message
          # I am using Recap Time Bot's GH public data for commits
          user_name: 'Recap Time Bot'
          user_email: 'recaptime.madebythepins@gmail.com'
          full_commit_message: 'docs: Build success from commit ${{ github.event.head_commit.message }}'
