name: Create a test build before deploying

on: [ branches, pr ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip to latest version
        run: |
          python3 -m pip install --upgrade pip

      - name: Get the dependency cache directory
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - run: mkdocs build

      - name: Cache Mkdocs test builds
        uses: actions/upload-artifact@v1
        with:
          name: Documentation Site Builds
          path: site